// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcCJhQIOtR0bAF_h6-K_leUylYh0QCJPY',
    appId: '1:1021090367447:web:3008c4533ae519e9b0ed92',
    messagingSenderId: '1021090367447',
    projectId: 'dreamtech-8138d',
    authDomain: 'dreamtech-8138d.firebaseapp.com',
    storageBucket: 'dreamtech-8138d.firebasestorage.app',
    measurementId: 'G-CGG86X7QZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0LAlUvWwwVVliugHNWHuPWcYDn1BQpps',
    appId: '1:1021090367447:android:707c5460d24c5c2fb0ed92',
    messagingSenderId: '1021090367447',
    projectId: 'dreamtech-8138d',
    storageBucket: 'dreamtech-8138d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDixulMSO73uNH5b3xhkvbASQzmCG4QiM',
    appId: '1:1021090367447:ios:4f027172e5c1f016b0ed92',
    messagingSenderId: '1021090367447',
    projectId: 'dreamtech-8138d',
    storageBucket: 'dreamtech-8138d.firebasestorage.app',
    iosBundleId: 'com.example.dreamTechFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDixulMSO73uNH5b3xhkvbASQzmCG4QiM',
    appId: '1:1021090367447:ios:4f027172e5c1f016b0ed92',
    messagingSenderId: '1021090367447',
    projectId: 'dreamtech-8138d',
    storageBucket: 'dreamtech-8138d.firebasestorage.app',
    iosBundleId: 'com.example.dreamTechFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcCJhQIOtR0bAF_h6-K_leUylYh0QCJPY',
    appId: '1:1021090367447:web:e747ed4c4032864ab0ed92',
    messagingSenderId: '1021090367447',
    projectId: 'dreamtech-8138d',
    authDomain: 'dreamtech-8138d.firebaseapp.com',
    storageBucket: 'dreamtech-8138d.firebasestorage.app',
    measurementId: 'G-D7L9LRWX53',
  );
}
